config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/cabinet'

  get 'pages/equipe'

  get 'pages/prestations'

  get 'pages/plateau'

  get 'pages/contact'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


Rails.application.routes.draw do
  get 'pages/cabinet'

  get 'pages/acces'

  get 'pages/horaires'

  get 'pages/info_pratiques'

  get 'pages/salles_de_soins'

  root to: 'pages#cabinet'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def cabinet
  end

  def acces
  end

  def horaires
  end

  def info_pratiques
  end

  def salles_de_soins
  end

  def equipe
  end

  def prestations
  end

  def plateau
  end

  def contact
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def cabinet
  end

  def acces
  end

  def horaires
  end

  def info_pratiques
  end

  def salles_de_soins
  end


  def equipe
  end

  def prestations
  end

  def plateau
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= javascript_include_tag 'application' %>
  </body>

   <body>
  <%= render 'shared/navbar' %>
 <!--  <% if current_page?(root_path) %>
    <p class="notice hidden"><%= notice %></p>
    <p class="alert hidden"><%= alert %></p>
  <% else %>
    <p class="notice hidden"><%= notice %></p>
    <p class="alert hidden"><%= alert %></p>
  <% end %> -->
    <%= yield %>
  <%= render "shared/footer" unless @disable_footer %>
<!--   <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %> -->
  <%= yield(:after_js) %>

  </body>
</html>

app/views/pages/acces.html.erb
acces au cabinet

app/views/pages/cabinet.html.erb
CABINET

<li>
	<%= link_to "Accès au cabinet", pages_acces_path %>
</li>
<li>
	<%= link_to "Horaires de consultation", pages_horaires_path %>
</li>
<li>
	<%= link_to "Informations pratiques", pages_info_pratiques_path %>
</li>
<li>
	<%= link_to "Nos salles de soins", pages_salles_de_soins_path %>
</li>

app/views/pages/contact.html.erb
CONTACT

app/views/pages/equipe.html.erb
EQUIPE

app/views/pages/horaires.html.erb
horaire de consultation

app/views/pages/info_pratiques.html.erb
INFOS PRATIQUES

app/views/pages/plateau.html.erb
PLATEAU TECHNIQUE 

app/views/pages/prestations.html.erb
prestations

app/views/pages/salles_de_soins.html.erb
SALLES DE SOINS

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer class="section bg-gray footer footer-sm">
  <div class="container">

    <div class="row">
      <div class="col-sm-12">
        <div class="text-center">
          <a class="navbar-brand logo" href="index.html">
            <span class="text-uppercase text-center">dentiste-lamouret</span>
          </a>

        <!--   <ul class="list-inline social-circle">
            <li><a href="http://www.facebook.com/dogtimecommunity" target="_blank"> <i class="zmdi zmdi-facebook"></i> </a></li>
            <li><a href="http://twitter.com/dogtimeco" target="_blank"> <i class="zmdi zmdi-twitter"></i> </a></li>
            <li><a href="http://www.instagram.com/dogtimecommunity/" target="_blank"> <i class="zmdi zmdi-instagram"></i> </a></li>
          </ul> -->

          <ul class="list-inline menu-list m-t-30">
            <li><a href=""> About Us</a></li>
            <li><a href=""> Help & Support</a></li>
            <li><a href=""> Terms & Conditions</a></li>
            <li><a href=""> Privacy Policy</a></li>
          </ul>

          <p class="text-muted m-b-0"> © dentiste-lamouret 2017 - All Right Reserved </p>

        </div>
      </div>
    </div>
    <!-- end row -->

  </div>
</footer>

<!-- END FOOTER -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-custom navbar-fixed-top" style="background-color: #F1F2F2; padding-bottom: 30px;" role="navigation">
  <div class="container">

    <!-- Navbar-header -->
    <div class="navbar-header">
      <!-- Responsive menu button -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <i class="zmdi zmdi-menu"></i>
      </button>


      <!-- LOGO -->
      <%= link_to "#{image_tag("tooth.png", :size => '50x50', class: "zmdi zmdi-navigation")}".html_safe, root_path, class: "navbar-brand logo" %>


    </div>
    <!-- end navbar-header -->

    <!-- menu -->
    <div class="navbar-collapse collapse" id="navbar-menu">
    
        <!-- Navbar left -->
          <ul class="nav navbar-nav nav-right">
            <li>
              <%= link_to "Le Cabinet", pages_cabinet_path %>
            </li>
            <li>
              <%= link_to "Notre Équipe", pages_equipe_path %>
            </li>
            <li>
              <%= link_to "Prestations", pages_prestations_path %>
            </li>
            <li>
              <%= link_to "Plateau Technique", pages_plateau_path %>
            </li>
            <li>
              <%= link_to "Contact", pages_contact_path %>
            </li>
        </ul>
    </div>

  </div>

    <!--/Menu -->
</div>
      <!-- end container -->
</div>
</div>
  <!-- End navbar-custom -->

app/views/static_pages/cabinet.html.erb
<h1>StaticPages#cabinet</h1>
<p>Find me in app/views/static_pages/cabinet.html.erb</p>

<li>
	<%= link_to "Accès au cabinet", pages_acces_path %>
</li>
<li>
	<%= link_to "Horaires de consultation", pages_horaires_path %>
</li>
<li>
	<%= link_to "Informations pratiques", pages_info_pratiques_path %>
</li>
<li>
	<%= link_to "Nos salles de soins", pages_salles_de_soins_path %>
</li>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<li>
	<%= link_to "Accueil", pages_home_path %>
</li>
<li>
	<%= link_to "Le Cabinet", pages_cabinet_path %>
</li>
<li>
	<%= link_to "Notre Équipe", pages_equipe_path %>
</li>
<li>
	<%= link_to "Prestations", pages_prestations_path %>
</li>
<li>
	<%= link_to "Plateau Technique", pages_plateau_path %>
</li>
<li>
	<%= link_to "Contact", pages_contact_path %>
</li>